config/routes.rb
Throwdown::Application.routes.draw do

  root 'games#new'

  resources :games do
    resources :scores do
      resources :rolls
    end
  end  

  post 'games/:game_id/scores/:score_id/rolls/:id' => "rolls#update"  
  
  get 'dice' => 'rolls#new_dice'
  
  post 'finish/games/:game_id/scores/:score_id/rolls/:id', to: "rolls#finished", as: 'finish'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :scores
	has_many :rolls, through: :scores


    def winner
      array = []
      winner = self.scores[0].points <= self.scores[1].points
      if winner
        [self.scores[1],self.scores[0]]
      else  
        [self.scores[0],self.scores[1]]
      end  
    end	
end

app/models/roll.rb
class Roll < ActiveRecord::Base
    belongs_to :score
    has_one :game, through: :score
    before_save :set_values

def throw_dice
  score =[]
  self.dice_left.times do 
  	score << rand(1..6)
  end	
  score
end	


def set_values
  self.dice_left ||= 6
  self.points ||= 0
  self.hot_dice ||=0
end  




  def count_up(array)
    array = array.collect{|s| s.to_i}
    freq = array.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    array = array.sort_by { |v| freq[v] }
    last_number = array.last
    if array.last(3) == [1,1,1]
      self.points = self.points + 1000
      p self.points
      array.pop(3)
      self.dice_left = self.dice_left - 3
      self.hot_dice = self.hot_dice + 3
      count_up(array)
    elsif array.last(3) == [last_number,last_number,last_number]
      self.points = self.points + (last_number.to_s + "00").to_i
      array.pop(3)
      self.dice_left = self.dice_left - 3
      self.hot_dice = self.hot_dice + 3
      count_up(array)
    else 
      if array != []	
        array.each do |x|
          self.dice_left = self.dice_left - 1
          if x == 5
    	    self.points = self.points +  50
    	    self.hot_dice = self.hot_dice + 1
    	  elsif x == 1
    	    self.points = self.points +  100
    	    self.hot_dice = self.hot_dice + 1
        else 
          @remainder =true  
    	  end
        end 
      end    	    
    end 
    if self.hot_dice == 6
        self.dice_left = 6	
        self.hot_dice = 0
    end
    if @remainder == true
      p @remainder
    else
      self.save
      self.points
    end  
    self.points

  end	

 


end

app/models/score.rb
class Score < ActiveRecord::Base
	has_many :rolls
	belongs_to :game
	before_save :set_values

end

def set_values
  self.points ||= 0
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.limit(10)
  end  



  def show
   @game = Game.find(params[:id])
   @scores = @game.scores
   @score1 = @scores[0]
   @score2 = @scores[1]
   @roll1 = @score1.rolls
   @roll2 = @score2.rolls 
   count = @score1.rolls.length
   @count = count - 1
   p @count 
  end	

  def new
	@game = Game.new
  end

  def create
   score = params["game"]["finishing_score"]
   @game = Game.create(:finishing_score => score.to_i)
   redirect_to new_game_score_path(@game)
  end	




end	

app/controllers/rolls_controller.rb
class RollsController < ApplicationController

  def index

  end	

  def create

  	@roll = Roll.create(score_id: params[:score_id])
  	redirect_to game_score_roll_path(params[:game_id],params[:score_id],@roll)
  end	

  def show
    @game = Game.find(params[:game_id])
  	@roll = Roll.find(params[:id])
  	@score = Score.find(params[:score_id])
  	@dice = @roll.throw_dice
    duplicate = @game.scores.all
    duplicate.delete(@score)
    @next_player = duplicate.first
    if request.xhr?
      render :json => {:dice => @dice }
    else

    end
  end	

 def update
  @roll = Roll.find(params[:id])
  first_value = @roll.points
  @score  = @roll.count_up(params[:data])
  updated_value = @roll.points
  p @roll.changed?
  if first_value == updated_value || @roll.changed? == true
  	@different = false
    render :json => {:data => @roll.points_was, :updated => @different }
  else
  	@different = true
    render :json => {:data => @score, :updated => @different }
  end
 end

 def finished
   @roll = Roll.find(params[:id])
   @score = Score.find(params[:score_id])
   @game = Game.find(params[:game_id])
   duplicate = @game.scores.all
   duplicate.delete(@score)
   next_player = duplicate.first
   if params[:scored_points] == "true"
     @score.points = @score.points + @roll.points
   else
   	 @roll.points = 0
   	 @roll.save
   end
   @score.save
   if @score.points >= @game.finishing_score
     redirect_to game_path(@game)
   else	
     redirect_to game_score_path(@game,next_player)
   end  
 end


 def new_dice
   @dice = [rand(1..6),rand(1..6),rand(1..6),rand(1..6),rand(1..6),rand(1..6)]
   render :partial => 'new_dice'
 end	



end	

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  
  def show
    @game = Game.find(params[:game_id])
    @score = Score.find(params[:id])
    @roll = Roll.new
  end	


  def new
    @game = Game.find(params[:game_id])	
  end

  def create
  	@score1 = Score.create(game_id:params[:game_id], name:params[:name1])
  	@score2 = Score.create(game_id:params[:game_id], name:params[:name2])
    
    redirect_to game_score_path(params[:game_id], @score1)


  end


end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="container_stats">
<table>
  <tr>
    <th>winner</th>
    <th>loser</th>
    <th>Score</th>
  </tr>
<% @games.each do |g|%>
  <% game_array = g.winner%>
  <tr>
    <td><%= game_array[0].name %></td>
    <td><%= game_array[1].name %></td>
    <td><%= game_array[0].points%> - <%= game_array[1].points%></td>
    
  </tr>  

<%end%>
</table>
</div>

app/views/games/new.html.erb
<div class="container">
  <h1 id="banner">Hot Dice</h1>
  <div class="front">
  <%= form_for @game do |f|%>
    <%= f.label :finishing_score%>
    <%= f.select :finishing_score, options_for_select([1000,2000,5000,10000,20000,50000]) %>
    <%= f.submit %>
  <% end %>
  </div>
</div>	

app/views/games/show.html.erb
<div class="container_stats">
  <h1>game stats</h1>
  <table>
    <tr>
      <th></th>
      <th><%= @score1.name%></th>
      <th><%= @score2.name %></th>
    </tr>	
    <% 0.upto(@count) do |i| %>
  
   <tr>
     <td>Roll <%= i%></td>
   <%if @roll1[i] != nil %>
      <td><%= @roll1[i].points%></td>
   <%end%>
   <%if @roll2[i] != nil %>
      <td><%= @roll2[i].points%></td>
   <%end%>   

    </tr>
  <%end%> 
  <tr>
    <th>Totals</th>
    <th><%= @score1.points%></th>
    <th><%= @score2.points %></th>
  </tr> 
</table>
</div>

app/views/layouts/_header.html.erb
  <div class="nav_container">
    <nav>
      <h1>HD</h1>
      <ul>
        <li><a href="/">Home</a></li>
        <li><%= link_to "Past Games", games_path%></li>
        <li><a href="/">Quit</a></li>
      </ul>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Throwdown</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,800' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/rolls/_new_dice.html.erb
<div class="images">
  <% @dice.each do |d| %>
    <%= image_tag(d.to_s + ".png", class:"nonselected",value:d)%>
  <%end%>  
</div>

app/views/rolls/show.html.erb
<div class="score_board">
  <p id="me">Your current total is: <%= @score.points%></p>
  <p id="you"><%= @next_player.name %>'s total is: <%= @next_player.points%></p>
</div>
<h2 id="points"><%= @roll.points%></h2>
<h2 id="error"></h2>
<h3 id="player_prompt">It's your turn <%= @score.name%></h3>
<div class="container_dice">
  <div class="total">
 
  </div>
  <div class="images">
	  <% @dice.each do |d| %>
	  <%= image_tag(d.to_s + ".png", class:"nonselected",value:d)%>
	  <%end%>  
  </div>	  

	  <%=form_for @roll,remote: true, url: game_score_roll_path(@game,@score,@roll), method: :patch do |f|%>
	    <%= f.submit "Score Dice!" %>
	  <%end%>

	  <%=form_tag(game_score_roll_path(@game,@score,@roll),class:"new_dice", method: :get,remote: true) do %>
	    <%= submit_tag("Roll Again")%>
	  <%end%>

	  <%=form_tag(finish_path(@game,@score,@roll)) do %>
	    <%= hidden_field_tag("scored_points", false)%>
	    <%= submit_tag("Finish Turn")%>
  <%end%>
 </div>

app/views/scores/new.html.erb
<div class="container">
  <div class="names">
  <%= form_tag(game_scores_path) do %>
    <ul>
    <li>
    <%= label_tag "Player 1" %>
    <%= text_field_tag :name1 %>
    </li>
    <li>
    <%= label_tag "Player 2" %>
    <%= text_field_tag :name2 %>
    </li>
    <%= hidden_field_tag(:game_id, @game.id) %>
	<%= submit_tag("Start Game", id: "save_names") %>
	</ul>
  <% end %>	
  </div>  
</div>

app/views/scores/show.html.erb
<div class="container">
  <h1>It's your turn <%= @score.name%></h1>
  <p>Your current total is <%= @score.points%> points</p>
  <%= form_for [@game,@score,@roll] do |f|%>
  <%= f.submit("Roll!") %>
  <%end%>	 
</div>